using System;
using System.ComponentModel;

namespace RFontAwesome
{
    public enum RFontAwesomeEnum
    {
		[Description("0")]
		None,
		[Description("0xf26e")]
		_500Px,
		[Description("0xf368")]
		AccessibleIcon,
		[Description("0xf369")]
		Accusoft,
		[Description("0xf2b9")]
		AddressBook,
		[Description("0xf2bb")]
		AddressCard,
		[Description("0xf042")]
		Adjust,
		[Description("0xf170")]
		Adn,
		[Description("0xf36a")]
		Adversal,
		[Description("0xf36b")]
		Affiliatetheme,
		[Description("0xf36c")]
		Algolia,
		[Description("0xf037")]
		AlignCenter,
		[Description("0xf039")]
		AlignJustify,
		[Description("0xf036")]
		AlignLeft,
		[Description("0xf038")]
		AlignRight,
		[Description("0xf461")]
		Allergies,
		[Description("0xf270")]
		Amazon,
		[Description("0xf42c")]
		AmazonPay,
		[Description("0xf0f9")]
		Ambulance,
		[Description("0xf2a3")]
		AmericanSignLanguageInterpreting,
		[Description("0xf36d")]
		Amilia,
		[Description("0xf13d")]
		Anchor,
		[Description("0xf17b")]
		Android,
		[Description("0xf209")]
		Angellist,
		[Description("0xf103")]
		AngleDoubleDown,
		[Description("0xf100")]
		AngleDoubleLeft,
		[Description("0xf101")]
		AngleDoubleRight,
		[Description("0xf102")]
		AngleDoubleUp,
		[Description("0xf107")]
		AngleDown,
		[Description("0xf104")]
		AngleLeft,
		[Description("0xf105")]
		AngleRight,
		[Description("0xf106")]
		AngleUp,
		[Description("0xf36e")]
		Angrycreative,
		[Description("0xf420")]
		Angular,
		[Description("0xf371")]
		Apper,
		[Description("0xf179")]
		Apple,
		[Description("0xf415")]
		ApplePay,
		[Description("0xf36f")]
		AppStore,
		[Description("0xf370")]
		AppStoreIos,
		[Description("0xf187")]
		Archive,
		[Description("0xf358")]
		ArrowAltCircleDown,
		[Description("0xf359")]
		ArrowAltCircleLeft,
		[Description("0xf35a")]
		ArrowAltCircleRight,
		[Description("0xf35b")]
		ArrowAltCircleUp,
		[Description("0xf0ab")]
		ArrowCircleDown,
		[Description("0xf0a8")]
		ArrowCircleLeft,
		[Description("0xf0a9")]
		ArrowCircleRight,
		[Description("0xf0aa")]
		ArrowCircleUp,
		[Description("0xf063")]
		ArrowDown,
		[Description("0xf060")]
		ArrowLeft,
		[Description("0xf061")]
		ArrowRight,
		[Description("0xf0b2")]
		ArrowsAlt,
		[Description("0xf337")]
		ArrowsAltH,
		[Description("0xf338")]
		ArrowsAltV,
		[Description("0xf062")]
		ArrowUp,
		[Description("0xf2a2")]
		AssistiveListeningSystems,
		[Description("0xf069")]
		Asterisk,
		[Description("0xf372")]
		Asymmetrik,
		[Description("0xf1fa")]
		At,
		[Description("0xf373")]
		Audible,
		[Description("0xf29e")]
		AudioDescription,
		[Description("0xf41c")]
		Autoprefixer,
		[Description("0xf374")]
		Avianex,
		[Description("0xf421")]
		Aviato,
		[Description("0xf375")]
		Aws,
		[Description("0xf04a")]
		Backward,
		[Description("0xf24e")]
		BalanceScale,
		[Description("0xf05e")]
		Ban,
		[Description("0xf462")]
		BandAid,
		[Description("0xf2d5")]
		Bandcamp,
		[Description("0xf02a")]
		Barcode,
		[Description("0xf0c9")]
		Bars,
		[Description("0xf433")]
		BaseballBall,
		[Description("0xf434")]
		BasketballBall,
		[Description("0xf2cd")]
		Bath,
		[Description("0xf244")]
		BatteryEmpty,
		[Description("0xf240")]
		BatteryFull,
		[Description("0xf242")]
		BatteryHalf,
		[Description("0xf243")]
		BatteryQuarter,
		[Description("0xf241")]
		BatteryThreeQuarters,
		[Description("0xf236")]
		Bed,
		[Description("0xf0fc")]
		Beer,
		[Description("0xf1b4")]
		Behance,
		[Description("0xf1b5")]
		BehanceSquare,
		[Description("0xf0f3")]
		Bell,
		[Description("0xf1f6")]
		BellSlash,
		[Description("0xf206")]
		Bicycle,
		[Description("0xf378")]
		Bimobject,
		[Description("0xf1e5")]
		Binoculars,
		[Description("0xf1fd")]
		BirthdayCake,
		[Description("0xf171")]
		Bitbucket,
		[Description("0xf379")]
		Bitcoin,
		[Description("0xf37a")]
		Bity,
		[Description("0xf37b")]
		Blackberry,
		[Description("0xf27e")]
		BlackTie,
		[Description("0xf517")]
		Blender,
		[Description("0xf29d")]
		Blind,
		[Description("0xf37c")]
		Blogger,
		[Description("0xf37d")]
		BloggerB,
		[Description("0xf293")]
		Bluetooth,
		[Description("0xf294")]
		BluetoothB,
		[Description("0xf032")]
		Bold,
		[Description("0xf0e7")]
		Bolt,
		[Description("0xf1e2")]
		Bomb,
		[Description("0xf02d")]
		Book,
		[Description("0xf02e")]
		Bookmark,
		[Description("0xf518")]
		BookOpen,
		[Description("0xf436")]
		BowlingBall,
		[Description("0xf466")]
		Box,
		[Description("0xf468")]
		Boxes,
		[Description("0xf49e")]
		BoxOpen,
		[Description("0xf2a1")]
		Braille,
		[Description("0xf0b1")]
		Briefcase,
		[Description("0xf469")]
		BriefcaseMedical,
		[Description("0xf519")]
		BroadcastTower,
		[Description("0xf51a")]
		Broom,
		[Description("0xf15a")]
		Btc,
		[Description("0xf188")]
		Bug,
		[Description("0xf1ad")]
		Building,
		[Description("0xf0a1")]
		Bullhorn,
		[Description("0xf140")]
		Bullseye,
		[Description("0xf46a")]
		Burn,
		[Description("0xf37f")]
		Buromobelexperte,
		[Description("0xf207")]
		Bus,
		[Description("0xf20d")]
		Buysellads,
		[Description("0xf1ec")]
		Calculator,
		[Description("0xf133")]
		Calendar,
		[Description("0xf073")]
		CalendarAlt,
		[Description("0xf274")]
		CalendarCheck,
		[Description("0xf272")]
		CalendarMinus,
		[Description("0xf271")]
		CalendarPlus,
		[Description("0xf273")]
		CalendarTimes,
		[Description("0xf030")]
		Camera,
		[Description("0xf083")]
		CameraRetro,
		[Description("0xf46b")]
		Capsules,
		[Description("0xf1b9")]
		Car,
		[Description("0xf0d7")]
		CaretDown,
		[Description("0xf0d9")]
		CaretLeft,
		[Description("0xf0da")]
		CaretRight,
		[Description("0xf150")]
		CaretSquareDown,
		[Description("0xf191")]
		CaretSquareLeft,
		[Description("0xf152")]
		CaretSquareRight,
		[Description("0xf151")]
		CaretSquareUp,
		[Description("0xf0d8")]
		CaretUp,
		[Description("0xf218")]
		CartArrowDown,
		[Description("0xf217")]
		CartPlus,
		[Description("0xf42d")]
		CcAmazonPay,
		[Description("0xf1f3")]
		CcAmex,
		[Description("0xf416")]
		CcApplePay,
		[Description("0xf24c")]
		CcDinersClub,
		[Description("0xf1f2")]
		CcDiscover,
		[Description("0xf24b")]
		CcJcb,
		[Description("0xf1f1")]
		CcMastercard,
		[Description("0xf1f4")]
		CcPaypal,
		[Description("0xf1f5")]
		CcStripe,
		[Description("0xf1f0")]
		CcVisa,
		[Description("0xf380")]
		Centercode,
		[Description("0xf0a3")]
		Certificate,
		[Description("0xf51b")]
		Chalkboard,
		[Description("0xf51c")]
		ChalkboardTeacher,
		[Description("0xf1fe")]
		ChartArea,
		[Description("0xf080")]
		ChartBar,
		[Description("0xf201")]
		ChartLine,
		[Description("0xf200")]
		ChartPie,
		[Description("0xf00c")]
		Check,
		[Description("0xf058")]
		CheckCircle,
		[Description("0xf14a")]
		CheckSquare,
		[Description("0xf439")]
		Chess,
		[Description("0xf43a")]
		ChessBishop,
		[Description("0xf43c")]
		ChessBoard,
		[Description("0xf43f")]
		ChessKing,
		[Description("0xf441")]
		ChessKnight,
		[Description("0xf443")]
		ChessPawn,
		[Description("0xf445")]
		ChessQueen,
		[Description("0xf447")]
		ChessRook,
		[Description("0xf13a")]
		ChevronCircleDown,
		[Description("0xf137")]
		ChevronCircleLeft,
		[Description("0xf138")]
		ChevronCircleRight,
		[Description("0xf139")]
		ChevronCircleUp,
		[Description("0xf078")]
		ChevronDown,
		[Description("0xf053")]
		ChevronLeft,
		[Description("0xf054")]
		ChevronRight,
		[Description("0xf077")]
		ChevronUp,
		[Description("0xf1ae")]
		Child,
		[Description("0xf268")]
		Chrome,
		[Description("0xf51d")]
		Church,
		[Description("0xf111")]
		Circle,
		[Description("0xf1ce")]
		CircleNotch,
		[Description("0xf328")]
		Clipboard,
		[Description("0xf46c")]
		ClipboardCheck,
		[Description("0xf46d")]
		ClipboardList,
		[Description("0xf017")]
		Clock,
		[Description("0xf24d")]
		Clone,
		[Description("0xf20a")]
		ClosedCaptioning,
		[Description("0xf0c2")]
		Cloud,
		[Description("0xf381")]
		CloudDownloadAlt,
		[Description("0xf383")]
		Cloudscale,
		[Description("0xf384")]
		Cloudsmith,
		[Description("0xf382")]
		CloudUploadAlt,
		[Description("0xf385")]
		Cloudversify,
		[Description("0xf121")]
		Code,
		[Description("0xf126")]
		CodeBranch,
		[Description("0xf1cb")]
		Codepen,
		[Description("0xf284")]
		Codiepie,
		[Description("0xf0f4")]
		Coffee,
		[Description("0xf013")]
		Cog,
		[Description("0xf085")]
		Cogs,
		[Description("0xf51e")]
		Coins,
		[Description("0xf0db")]
		Columns,
		[Description("0xf075")]
		Comment,
		[Description("0xf27a")]
		CommentAlt,
		[Description("0xf4ad")]
		CommentDots,
		[Description("0xf086")]
		Comments,
		[Description("0xf4b3")]
		CommentSlash,
		[Description("0xf51f")]
		CompactDisc,
		[Description("0xf14e")]
		Compass,
		[Description("0xf066")]
		Compress,
		[Description("0xf20e")]
		Connectdevelop,
		[Description("0xf26d")]
		Contao,
		[Description("0xf0c5")]
		Copy,
		[Description("0xf1f9")]
		Copyright,
		[Description("0xf4b8")]
		Couch,
		[Description("0xf388")]
		Cpanel,
		[Description("0xf25e")]
		CreativeCommons,
		[Description("0xf4e7")]
		CreativeCommonsBy,
		[Description("0xf4e8")]
		CreativeCommonsNc,
		[Description("0xf4e9")]
		CreativeCommonsNcEu,
		[Description("0xf4ea")]
		CreativeCommonsNcJp,
		[Description("0xf4eb")]
		CreativeCommonsNd,
		[Description("0xf4ec")]
		CreativeCommonsPd,
		[Description("0xf4ed")]
		CreativeCommonsPdAlt,
		[Description("0xf4ee")]
		CreativeCommonsRemix,
		[Description("0xf4ef")]
		CreativeCommonsSa,
		[Description("0xf4f0")]
		CreativeCommonsSampling,
		[Description("0xf4f1")]
		CreativeCommonsSamplingPlus,
		[Description("0xf4f2")]
		CreativeCommonsShare,
		[Description("0xf09d")]
		CreditCard,
		[Description("0xf125")]
		Crop,
		[Description("0xf05b")]
		Crosshairs,
		[Description("0xf520")]
		Crow,
		[Description("0xf521")]
		Crown,
		[Description("0xf13c")]
		Css3,
		[Description("0xf38b")]
		Css3Alt,
		[Description("0xf1b2")]
		Cube,
		[Description("0xf1b3")]
		Cubes,
		[Description("0xf0c4")]
		Cut,
		[Description("0xf38c")]
		Cuttlefish,
		[Description("0xf38d")]
		DAndD,
		[Description("0xf210")]
		Dashcube,
		[Description("0xf1c0")]
		Database,
		[Description("0xf2a4")]
		Deaf,
		[Description("0xf1a5")]
		Delicious,
		[Description("0xf38e")]
		Deploydog,
		[Description("0xf38f")]
		Deskpro,
		[Description("0xf108")]
		Desktop,
		[Description("0xf1bd")]
		Deviantart,
		[Description("0xf470")]
		Diagnoses,
		[Description("0xf522")]
		Dice,
		[Description("0xf523")]
		DiceFive,
		[Description("0xf524")]
		DiceFour,
		[Description("0xf525")]
		DiceOne,
		[Description("0xf526")]
		DiceSix,
		[Description("0xf527")]
		DiceThree,
		[Description("0xf528")]
		DiceTwo,
		[Description("0xf1a6")]
		Digg,
		[Description("0xf391")]
		DigitalOcean,
		[Description("0xf392")]
		Discord,
		[Description("0xf393")]
		Discourse,
		[Description("0xf529")]
		Divide,
		[Description("0xf471")]
		Dna,
		[Description("0xf394")]
		Dochub,
		[Description("0xf395")]
		Docker,
		[Description("0xf155")]
		DollarSign,
		[Description("0xf472")]
		Dolly,
		[Description("0xf474")]
		DollyFlatbed,
		[Description("0xf4b9")]
		Donate,
		[Description("0xf52a")]
		DoorClosed,
		[Description("0xf52b")]
		DoorOpen,
		[Description("0xf192")]
		DotCircle,
		[Description("0xf4ba")]
		Dove,
		[Description("0xf019")]
		Download,
		[Description("0xf396")]
		Draft2digital,
		[Description("0xf17d")]
		Dribbble,
		[Description("0xf397")]
		DribbbleSquare,
		[Description("0xf16b")]
		Dropbox,
		[Description("0xf1a9")]
		Drupal,
		[Description("0xf44b")]
		Dumbbell,
		[Description("0xf399")]
		Dyalog,
		[Description("0xf39a")]
		Earlybirds,
		[Description("0xf4f4")]
		Ebay,
		[Description("0xf282")]
		Edge,
		[Description("0xf044")]
		Edit,
		[Description("0xf052")]
		Eject,
		[Description("0xf430")]
		Elementor,
		[Description("0xf141")]
		EllipsisH,
		[Description("0xf142")]
		EllipsisV,
		[Description("0xf423")]
		Ember,
		[Description("0xf1d1")]
		Empire,
		[Description("0xf0e0")]
		Envelope,
		[Description("0xf2b6")]
		EnvelopeOpen,
		[Description("0xf199")]
		EnvelopeSquare,
		[Description("0xf299")]
		Envira,
		[Description("0xf52c")]
		Equals,
		[Description("0xf12d")]
		Eraser,
		[Description("0xf39d")]
		Erlang,
		[Description("0xf42e")]
		Ethereum,
		[Description("0xf2d7")]
		Etsy,
		[Description("0xf153")]
		EuroSign,
		[Description("0xf362")]
		ExchangeAlt,
		[Description("0xf12a")]
		Exclamation,
		[Description("0xf06a")]
		ExclamationCircle,
		[Description("0xf071")]
		ExclamationTriangle,
		[Description("0xf065")]
		Expand,
		[Description("0xf31e")]
		ExpandArrowsAlt,
		[Description("0xf23e")]
		Expeditedssl,
		[Description("0xf35d")]
		ExternalLinkAlt,
		[Description("0xf360")]
		ExternalLinkSquareAlt,
		[Description("0xf06e")]
		Eye,
		[Description("0xf1fb")]
		EyeDropper,
		[Description("0xf070")]
		EyeSlash,
		[Description("0xf09a")]
		Facebook,
		[Description("0xf39e")]
		FacebookF,
		[Description("0xf39f")]
		FacebookMessenger,
		[Description("0xf082")]
		FacebookSquare,
		[Description("0xf049")]
		FastBackward,
		[Description("0xf050")]
		FastForward,
		[Description("0xf1ac")]
		Fax,
		[Description("0xf52d")]
		Feather,
		[Description("0xf182")]
		Female,
		[Description("0xf0fb")]
		FighterJet,
		[Description("0xf15b")]
		File,
		[Description("0xf15c")]
		FileAlt,
		[Description("0xf1c6")]
		FileArchive,
		[Description("0xf1c7")]
		FileAudio,
		[Description("0xf1c9")]
		FileCode,
		[Description("0xf1c3")]
		FileExcel,
		[Description("0xf1c5")]
		FileImage,
		[Description("0xf477")]
		FileMedical,
		[Description("0xf478")]
		FileMedicalAlt,
		[Description("0xf1c1")]
		FilePdf,
		[Description("0xf1c4")]
		FilePowerpoint,
		[Description("0xf1c8")]
		FileVideo,
		[Description("0xf1c2")]
		FileWord,
		[Description("0xf008")]
		Film,
		[Description("0xf0b0")]
		Filter,
		[Description("0xf06d")]
		Fire,
		[Description("0xf134")]
		FireExtinguisher,
		[Description("0xf269")]
		Firefox,
		[Description("0xf479")]
		FirstAid,
		[Description("0xf3a1")]
		Firstdraft,
		[Description("0xf2b0")]
		FirstOrder,
		[Description("0xf50a")]
		FirstOrderAlt,
		[Description("0xf024")]
		Flag,
		[Description("0xf11e")]
		FlagCheckered,
		[Description("0xf0c3")]
		Flask,
		[Description("0xf16e")]
		Flickr,
		[Description("0xf44d")]
		Flipboard,
		[Description("0xf417")]
		Fly,
		[Description("0xf07b")]
		Folder,
		[Description("0xf07c")]
		FolderOpen,
		[Description("0xf031")]
		Font,
		[Description("0xf2b4")]
		FontAwesome,
		[Description("0xf35c")]
		FontAwesomeAlt,
		[Description("0xf425")]
		FontAwesomeFlag,
		[Description("0xf4e6")]
		FontAwesomeLogoFull,
		[Description("0xf280")]
		Fonticons,
		[Description("0xf3a2")]
		FonticonsFi,
		[Description("0xf44e")]
		FootballBall,
		[Description("0xf286")]
		FortAwesome,
		[Description("0xf3a3")]
		FortAwesomeAlt,
		[Description("0xf211")]
		Forumbee,
		[Description("0xf04e")]
		Forward,
		[Description("0xf180")]
		Foursquare,
		[Description("0xf3a4")]
		Freebsd,
		[Description("0xf2c5")]
		FreeCodeCamp,
		[Description("0xf52e")]
		Frog,
		[Description("0xf119")]
		Frown,
		[Description("0xf50b")]
		Fulcrum,
		[Description("0xf1e3")]
		Futbol,
		[Description("0xf50c")]
		GalacticRepublic,
		[Description("0xf50d")]
		GalacticSenate,
		[Description("0xf11b")]
		Gamepad,
		[Description("0xf52f")]
		GasPump,
		[Description("0xf0e3")]
		Gavel,
		[Description("0xf3a5")]
		Gem,
		[Description("0xf22d")]
		Genderless,
		[Description("0xf265")]
		GetPocket,
		[Description("0xf260")]
		Gg,
		[Description("0xf261")]
		GgCircle,
		[Description("0xf06b")]
		Gift,
		[Description("0xf1d3")]
		Git,
		[Description("0xf09b")]
		Github,
		[Description("0xf113")]
		GithubAlt,
		[Description("0xf092")]
		GithubSquare,
		[Description("0xf3a6")]
		Gitkraken,
		[Description("0xf296")]
		Gitlab,
		[Description("0xf1d2")]
		GitSquare,
		[Description("0xf426")]
		Gitter,
		[Description("0xf530")]
		Glasses,
		[Description("0xf000")]
		GlassMartini,
		[Description("0xf2a5")]
		Glide,
		[Description("0xf2a6")]
		GlideG,
		[Description("0xf0ac")]
		Globe,
		[Description("0xf3a7")]
		Gofore,
		[Description("0xf450")]
		GolfBall,
		[Description("0xf3a8")]
		Goodreads,
		[Description("0xf3a9")]
		GoodreadsG,
		[Description("0xf1a0")]
		Google,
		[Description("0xf3aa")]
		GoogleDrive,
		[Description("0xf3ab")]
		GooglePlay,
		[Description("0xf2b3")]
		GooglePlus,
		[Description("0xf0d5")]
		GooglePlusG,
		[Description("0xf0d4")]
		GooglePlusSquare,
		[Description("0xf1ee")]
		GoogleWallet,
		[Description("0xf19d")]
		GraduationCap,
		[Description("0xf184")]
		Gratipay,
		[Description("0xf2d6")]
		Grav,
		[Description("0xf531")]
		GreaterThan,
		[Description("0xf532")]
		GreaterThanEqual,
		[Description("0xf3ac")]
		Gripfire,
		[Description("0xf3ad")]
		Grunt,
		[Description("0xf3ae")]
		Gulp,
		[Description("0xf1d4")]
		HackerNews,
		[Description("0xf3af")]
		HackerNewsSquare,
		[Description("0xf4bd")]
		HandHolding,
		[Description("0xf4be")]
		HandHoldingHeart,
		[Description("0xf4c0")]
		HandHoldingUsd,
		[Description("0xf258")]
		HandLizard,
		[Description("0xf256")]
		HandPaper,
		[Description("0xf25b")]
		HandPeace,
		[Description("0xf0a7")]
		HandPointDown,
		[Description("0xf25a")]
		HandPointer,
		[Description("0xf0a5")]
		HandPointLeft,
		[Description("0xf0a4")]
		HandPointRight,
		[Description("0xf0a6")]
		HandPointUp,
		[Description("0xf255")]
		HandRock,
		[Description("0xf4c2")]
		Hands,
		[Description("0xf257")]
		HandScissors,
		[Description("0xf2b5")]
		Handshake,
		[Description("0xf4c4")]
		HandsHelping,
		[Description("0xf259")]
		HandSpock,
		[Description("0xf292")]
		Hashtag,
		[Description("0xf0a0")]
		Hdd,
		[Description("0xf1dc")]
		Heading,
		[Description("0xf025")]
		Headphones,
		[Description("0xf004")]
		Heart,
		[Description("0xf21e")]
		Heartbeat,
		[Description("0xf533")]
		Helicopter,
		[Description("0xf452")]
		Hips,
		[Description("0xf3b0")]
		HireAHelper,
		[Description("0xf1da")]
		History,
		[Description("0xf453")]
		HockeyPuck,
		[Description("0xf015")]
		Home,
		[Description("0xf427")]
		Hooli,
		[Description("0xf0f8")]
		Hospital,
		[Description("0xf47d")]
		HospitalAlt,
		[Description("0xf47e")]
		HospitalSymbol,
		[Description("0xf3b1")]
		Hotjar,
		[Description("0xf254")]
		Hourglass,
		[Description("0xf253")]
		HourglassEnd,
		[Description("0xf252")]
		HourglassHalf,
		[Description("0xf251")]
		HourglassStart,
		[Description("0xf27c")]
		Houzz,
		[Description("0xf0fd")]
		HSquare,
		[Description("0xf13b")]
		Html5,
		[Description("0xf3b2")]
		Hubspot,
		[Description("0xf246")]
		ICursor,
		[Description("0xf2c1")]
		IdBadge,
		[Description("0xf2c2")]
		IdCard,
		[Description("0xf47f")]
		IdCardAlt,
		[Description("0xf03e")]
		Image,
		[Description("0xf302")]
		Images,
		[Description("0xf2d8")]
		Imdb,
		[Description("0xf01c")]
		Inbox,
		[Description("0xf03c")]
		Indent,
		[Description("0xf275")]
		Industry,
		[Description("0xf534")]
		Infinity,
		[Description("0xf129")]
		Info,
		[Description("0xf05a")]
		InfoCircle,
		[Description("0xf16d")]
		Instagram,
		[Description("0xf26b")]
		InternetExplorer,
		[Description("0xf208")]
		Ioxhost,
		[Description("0xf033")]
		Italic,
		[Description("0xf3b4")]
		Itunes,
		[Description("0xf3b5")]
		ItunesNote,
		[Description("0xf4e4")]
		Java,
		[Description("0xf50e")]
		JediOrder,
		[Description("0xf3b6")]
		Jenkins,
		[Description("0xf3b7")]
		Joget,
		[Description("0xf1aa")]
		Joomla,
		[Description("0xf3b8")]
		Js,
		[Description("0xf1cc")]
		Jsfiddle,
		[Description("0xf3b9")]
		JsSquare,
		[Description("0xf084")]
		Key,
		[Description("0xf4f5")]
		Keybase,
		[Description("0xf11c")]
		Keyboard,
		[Description("0xf3ba")]
		Keycdn,
		[Description("0xf3bb")]
		Kickstarter,
		[Description("0xf3bc")]
		KickstarterK,
		[Description("0xf535")]
		KiwiBird,
		[Description("0xf42f")]
		Korvue,
		[Description("0xf1ab")]
		Language,
		[Description("0xf109")]
		Laptop,
		[Description("0xf3bd")]
		Laravel,
		[Description("0xf202")]
		Lastfm,
		[Description("0xf203")]
		LastfmSquare,
		[Description("0xf06c")]
		Leaf,
		[Description("0xf212")]
		Leanpub,
		[Description("0xf094")]
		Lemon,
		[Description("0xf41d")]
		Less,
		[Description("0xf536")]
		LessThan,
		[Description("0xf537")]
		LessThanEqual,
		[Description("0xf3be")]
		LevelDownAlt,
		[Description("0xf3bf")]
		LevelUpAlt,
		[Description("0xf1cd")]
		LifeRing,
		[Description("0xf0eb")]
		Lightbulb,
		[Description("0xf3c0")]
		Line,
		[Description("0xf0c1")]
		Link,
		[Description("0xf08c")]
		Linkedin,
		[Description("0xf0e1")]
		LinkedinIn,
		[Description("0xf2b8")]
		Linode,
		[Description("0xf17c")]
		Linux,
		[Description("0xf195")]
		LiraSign,
		[Description("0xf03a")]
		List,
		[Description("0xf022")]
		ListAlt,
		[Description("0xf0cb")]
		ListOl,
		[Description("0xf0ca")]
		ListUl,
		[Description("0xf124")]
		LocationArrow,
		[Description("0xf023")]
		Lock,
		[Description("0xf3c1")]
		LockOpen,
		[Description("0xf309")]
		LongArrowAltDown,
		[Description("0xf30a")]
		LongArrowAltLeft,
		[Description("0xf30b")]
		LongArrowAltRight,
		[Description("0xf30c")]
		LongArrowAltUp,
		[Description("0xf2a8")]
		LowVision,
		[Description("0xf3c3")]
		Lyft,
		[Description("0xf3c4")]
		Magento,
		[Description("0xf0d0")]
		Magic,
		[Description("0xf076")]
		Magnet,
		[Description("0xf183")]
		Male,
		[Description("0xf50f")]
		Mandalorian,
		[Description("0xf279")]
		Map,
		[Description("0xf041")]
		MapMarker,
		[Description("0xf3c5")]
		MapMarkerAlt,
		[Description("0xf276")]
		MapPin,
		[Description("0xf277")]
		MapSigns,
		[Description("0xf222")]
		Mars,
		[Description("0xf227")]
		MarsDouble,
		[Description("0xf229")]
		MarsStroke,
		[Description("0xf22b")]
		MarsStrokeH,
		[Description("0xf22a")]
		MarsStrokeV,
		[Description("0xf4f6")]
		Mastodon,
		[Description("0xf136")]
		Maxcdn,
		[Description("0xf3c6")]
		Medapps,
		[Description("0xf23a")]
		Medium,
		[Description("0xf3c7")]
		MediumM,
		[Description("0xf0fa")]
		Medkit,
		[Description("0xf3c8")]
		Medrt,
		[Description("0xf2e0")]
		Meetup,
		[Description("0xf11a")]
		Meh,
		[Description("0xf538")]
		Memory,
		[Description("0xf223")]
		Mercury,
		[Description("0xf2db")]
		Microchip,
		[Description("0xf130")]
		Microphone,
		[Description("0xf3c9")]
		MicrophoneAlt,
		[Description("0xf539")]
		MicrophoneAltSlash,
		[Description("0xf131")]
		MicrophoneSlash,
		[Description("0xf3ca")]
		Microsoft,
		[Description("0xf068")]
		Minus,
		[Description("0xf056")]
		MinusCircle,
		[Description("0xf146")]
		MinusSquare,
		[Description("0xf3cb")]
		Mix,
		[Description("0xf289")]
		Mixcloud,
		[Description("0xf3cc")]
		Mizuni,
		[Description("0xf10b")]
		Mobile,
		[Description("0xf3cd")]
		MobileAlt,
		[Description("0xf285")]
		Modx,
		[Description("0xf3d0")]
		Monero,
		[Description("0xf0d6")]
		MoneyBill,
		[Description("0xf3d1")]
		MoneyBillAlt,
		[Description("0xf53a")]
		MoneyBillWave,
		[Description("0xf53b")]
		MoneyBillWaveAlt,
		[Description("0xf53c")]
		MoneyCheck,
		[Description("0xf53d")]
		MoneyCheckAlt,
		[Description("0xf186")]
		Moon,
		[Description("0xf21c")]
		Motorcycle,
		[Description("0xf245")]
		MousePointer,
		[Description("0xf001")]
		Music,
		[Description("0xf3d2")]
		Napster,
		[Description("0xf22c")]
		Neuter,
		[Description("0xf1ea")]
		Newspaper,
		[Description("0xf418")]
		NintendoSwitch,
		[Description("0xf419")]
		Node,
		[Description("0xf3d3")]
		NodeJs,
		[Description("0xf53e")]
		NotEqual,
		[Description("0xf481")]
		NotesMedical,
		[Description("0xf3d4")]
		Npm,
		[Description("0xf3d5")]
		Ns8,
		[Description("0xf3d6")]
		Nutritionix,
		[Description("0xf247")]
		ObjectGroup,
		[Description("0xf248")]
		ObjectUngroup,
		[Description("0xf263")]
		Odnoklassniki,
		[Description("0xf264")]
		OdnoklassnikiSquare,
		[Description("0xf510")]
		OldRepublic,
		[Description("0xf23d")]
		Opencart,
		[Description("0xf19b")]
		Openid,
		[Description("0xf26a")]
		Opera,
		[Description("0xf23c")]
		OptinMonster,
		[Description("0xf41a")]
		Osi,
		[Description("0xf03b")]
		Outdent,
		[Description("0xf3d7")]
		Page4,
		[Description("0xf18c")]
		Pagelines,
		[Description("0xf1fc")]
		PaintBrush,
		[Description("0xf53f")]
		Palette,
		[Description("0xf3d8")]
		Palfed,
		[Description("0xf482")]
		Pallet,
		[Description("0xf0c6")]
		Paperclip,
		[Description("0xf1d8")]
		PaperPlane,
		[Description("0xf4cd")]
		ParachuteBox,
		[Description("0xf1dd")]
		Paragraph,
		[Description("0xf540")]
		Parking,
		[Description("0xf0ea")]
		Paste,
		[Description("0xf3d9")]
		Patreon,
		[Description("0xf04c")]
		Pause,
		[Description("0xf28b")]
		PauseCircle,
		[Description("0xf1b0")]
		Paw,
		[Description("0xf1ed")]
		Paypal,
		[Description("0xf303")]
		PencilAlt,
		[Description("0xf14b")]
		PenSquare,
		[Description("0xf4ce")]
		PeopleCarry,
		[Description("0xf295")]
		Percent,
		[Description("0xf541")]
		Percentage,
		[Description("0xf3da")]
		Periscope,
		[Description("0xf3db")]
		Phabricator,
		[Description("0xf3dc")]
		PhoenixFramework,
		[Description("0xf511")]
		PhoenixSquadron,
		[Description("0xf095")]
		Phone,
		[Description("0xf3dd")]
		PhoneSlash,
		[Description("0xf098")]
		PhoneSquare,
		[Description("0xf2a0")]
		PhoneVolume,
		[Description("0xf457")]
		Php,
		[Description("0xf2ae")]
		PiedPiper,
		[Description("0xf1a8")]
		PiedPiperAlt,
		[Description("0xf4e5")]
		PiedPiperHat,
		[Description("0xf1a7")]
		PiedPiperPp,
		[Description("0xf4d3")]
		PiggyBank,
		[Description("0xf484")]
		Pills,
		[Description("0xf0d2")]
		Pinterest,
		[Description("0xf231")]
		PinterestP,
		[Description("0xf0d3")]
		PinterestSquare,
		[Description("0xf072")]
		Plane,
		[Description("0xf04b")]
		Play,
		[Description("0xf144")]
		PlayCircle,
		[Description("0xf3df")]
		Playstation,
		[Description("0xf1e6")]
		Plug,
		[Description("0xf067")]
		Plus,
		[Description("0xf055")]
		PlusCircle,
		[Description("0xf0fe")]
		PlusSquare,
		[Description("0xf2ce")]
		Podcast,
		[Description("0xf2fe")]
		Poo,
		[Description("0xf3e0")]
		Portrait,
		[Description("0xf154")]
		PoundSign,
		[Description("0xf011")]
		PowerOff,
		[Description("0xf485")]
		PrescriptionBottle,
		[Description("0xf486")]
		PrescriptionBottleAlt,
		[Description("0xf02f")]
		Print,
		[Description("0xf487")]
		Procedures,
		[Description("0xf288")]
		ProductHunt,
		[Description("0xf542")]
		ProjectDiagram,
		[Description("0xf3e1")]
		Pushed,
		[Description("0xf12e")]
		PuzzlePiece,
		[Description("0xf3e2")]
		Python,
		[Description("0xf1d6")]
		Qq,
		[Description("0xf029")]
		Qrcode,
		[Description("0xf128")]
		Question,
		[Description("0xf059")]
		QuestionCircle,
		[Description("0xf458")]
		Quidditch,
		[Description("0xf459")]
		Quinscape,
		[Description("0xf2c4")]
		Quora,
		[Description("0xf10d")]
		QuoteLeft,
		[Description("0xf10e")]
		QuoteRight,
		[Description("0xf074")]
		Random,
		[Description("0xf2d9")]
		Ravelry,
		[Description("0xf41b")]
		React,
		[Description("0xf4d5")]
		Readme,
		[Description("0xf1d0")]
		Rebel,
		[Description("0xf543")]
		Receipt,
		[Description("0xf1b8")]
		Recycle,
		[Description("0xf1a1")]
		Reddit,
		[Description("0xf281")]
		RedditAlien,
		[Description("0xf1a2")]
		RedditSquare,
		[Description("0xf01e")]
		Redo,
		[Description("0xf2f9")]
		RedoAlt,
		[Description("0xf3e3")]
		RedRiver,
		[Description("0xf25d")]
		Registered,
		[Description("0xf3e4")]
		Rendact,
		[Description("0xf18b")]
		Renren,
		[Description("0xf3e5")]
		Reply,
		[Description("0xf122")]
		ReplyAll,
		[Description("0xf3e6")]
		Replyd,
		[Description("0xf4f8")]
		Researchgate,
		[Description("0xf3e7")]
		Resolving,
		[Description("0xf079")]
		Retweet,
		[Description("0xf4d6")]
		Ribbon,
		[Description("0xf018")]
		Road,
		[Description("0xf544")]
		Robot,
		[Description("0xf135")]
		Rocket,
		[Description("0xf3e8")]
		Rocketchat,
		[Description("0xf3e9")]
		Rockrms,
		[Description("0xf4f7")]
		RProject,
		[Description("0xf09e")]
		Rss,
		[Description("0xf143")]
		RssSquare,
		[Description("0xf158")]
		RubleSign,
		[Description("0xf545")]
		Ruler,
		[Description("0xf546")]
		RulerCombined,
		[Description("0xf547")]
		RulerHorizontal,
		[Description("0xf548")]
		RulerVertical,
		[Description("0xf156")]
		RupeeSign,
		[Description("0xf267")]
		Safari,
		[Description("0xf41e")]
		Sass,
		[Description("0xf0c7")]
		Save,
		[Description("0xf3ea")]
		Schlix,
		[Description("0xf549")]
		School,
		[Description("0xf54a")]
		Screwdriver,
		[Description("0xf28a")]
		Scribd,
		[Description("0xf002")]
		Search,
		[Description("0xf3eb")]
		Searchengin,
		[Description("0xf010")]
		SearchMinus,
		[Description("0xf00e")]
		SearchPlus,
		[Description("0xf4d8")]
		Seedling,
		[Description("0xf2da")]
		Sellcast,
		[Description("0xf213")]
		Sellsy,
		[Description("0xf233")]
		Server,
		[Description("0xf3ec")]
		Servicestack,
		[Description("0xf064")]
		Share,
		[Description("0xf1e0")]
		ShareAlt,
		[Description("0xf1e1")]
		ShareAltSquare,
		[Description("0xf14d")]
		ShareSquare,
		[Description("0xf20b")]
		ShekelSign,
		[Description("0xf3ed")]
		ShieldAlt,
		[Description("0xf21a")]
		Ship,
		[Description("0xf48b")]
		ShippingFast,
		[Description("0xf214")]
		Shirtsinbulk,
		[Description("0xf54b")]
		ShoePrints,
		[Description("0xf290")]
		ShoppingBag,
		[Description("0xf291")]
		ShoppingBasket,
		[Description("0xf07a")]
		ShoppingCart,
		[Description("0xf2cc")]
		Shower,
		[Description("0xf4d9")]
		Sign,
		[Description("0xf012")]
		Signal,
		[Description("0xf2f6")]
		SignInAlt,
		[Description("0xf2a7")]
		SignLanguage,
		[Description("0xf2f5")]
		SignOutAlt,
		[Description("0xf215")]
		Simplybuilt,
		[Description("0xf3ee")]
		Sistrix,
		[Description("0xf0e8")]
		Sitemap,
		[Description("0xf512")]
		Sith,
		[Description("0xf54c")]
		Skull,
		[Description("0xf216")]
		Skyatlas,
		[Description("0xf17e")]
		Skype,
		[Description("0xf198")]
		Slack,
		[Description("0xf3ef")]
		SlackHash,
		[Description("0xf1de")]
		SlidersH,
		[Description("0xf1e7")]
		Slideshare,
		[Description("0xf118")]
		Smile,
		[Description("0xf48d")]
		Smoking,
		[Description("0xf54d")]
		SmokingBan,
		[Description("0xf2ab")]
		Snapchat,
		[Description("0xf2ac")]
		SnapchatGhost,
		[Description("0xf2ad")]
		SnapchatSquare,
		[Description("0xf2dc")]
		Snowflake,
		[Description("0xf0dc")]
		Sort,
		[Description("0xf15d")]
		SortAlphaDown,
		[Description("0xf15e")]
		SortAlphaUp,
		[Description("0xf160")]
		SortAmountDown,
		[Description("0xf161")]
		SortAmountUp,
		[Description("0xf0dd")]
		SortDown,
		[Description("0xf162")]
		SortNumericDown,
		[Description("0xf163")]
		SortNumericUp,
		[Description("0xf0de")]
		SortUp,
		[Description("0xf1be")]
		Soundcloud,
		[Description("0xf197")]
		SpaceShuttle,
		[Description("0xf3f3")]
		Speakap,
		[Description("0xf110")]
		Spinner,
		[Description("0xf1bc")]
		Spotify,
		[Description("0xf0c8")]
		Square,
		[Description("0xf45c")]
		SquareFull,
		[Description("0xf18d")]
		StackExchange,
		[Description("0xf16c")]
		StackOverflow,
		[Description("0xf005")]
		Star,
		[Description("0xf089")]
		StarHalf,
		[Description("0xf3f5")]
		Staylinked,
		[Description("0xf1b6")]
		Steam,
		[Description("0xf1b7")]
		SteamSquare,
		[Description("0xf3f6")]
		SteamSymbol,
		[Description("0xf048")]
		StepBackward,
		[Description("0xf051")]
		StepForward,
		[Description("0xf0f1")]
		Stethoscope,
		[Description("0xf3f7")]
		StickerMule,
		[Description("0xf249")]
		StickyNote,
		[Description("0xf04d")]
		Stop,
		[Description("0xf28d")]
		StopCircle,
		[Description("0xf2f2")]
		Stopwatch,
		[Description("0xf54e")]
		Store,
		[Description("0xf54f")]
		StoreAlt,
		[Description("0xf428")]
		Strava,
		[Description("0xf550")]
		Stream,
		[Description("0xf21d")]
		StreetView,
		[Description("0xf0cc")]
		Strikethrough,
		[Description("0xf429")]
		Stripe,
		[Description("0xf42a")]
		StripeS,
		[Description("0xf551")]
		Stroopwafel,
		[Description("0xf3f8")]
		Studiovinari,
		[Description("0xf1a4")]
		Stumbleupon,
		[Description("0xf1a3")]
		StumbleuponCircle,
		[Description("0xf12c")]
		Subscript,
		[Description("0xf239")]
		Subway,
		[Description("0xf0f2")]
		Suitcase,
		[Description("0xf185")]
		Sun,
		[Description("0xf2dd")]
		Superpowers,
		[Description("0xf12b")]
		Superscript,
		[Description("0xf3f9")]
		Supple,
		[Description("0xf021")]
		Sync,
		[Description("0xf2f1")]
		SyncAlt,
		[Description("0xf48e")]
		Syringe,
		[Description("0xf0ce")]
		Table,
		[Description("0xf10a")]
		Tablet,
		[Description("0xf3fa")]
		TabletAlt,
		[Description("0xf45d")]
		TableTennis,
		[Description("0xf490")]
		Tablets,
		[Description("0xf3fd")]
		TachometerAlt,
		[Description("0xf02b")]
		Tag,
		[Description("0xf02c")]
		Tags,
		[Description("0xf4db")]
		Tape,
		[Description("0xf0ae")]
		Tasks,
		[Description("0xf1ba")]
		Taxi,
		[Description("0xf4f9")]
		Teamspeak,
		[Description("0xf2c6")]
		Telegram,
		[Description("0xf3fe")]
		TelegramPlane,
		[Description("0xf1d5")]
		TencentWeibo,
		[Description("0xf120")]
		Terminal,
		[Description("0xf034")]
		TextHeight,
		[Description("0xf035")]
		TextWidth,
		[Description("0xf00a")]
		Th,
		[Description("0xf2b2")]
		Themeisle,
		[Description("0xf491")]
		Thermometer,
		[Description("0xf2cb")]
		ThermometerEmpty,
		[Description("0xf2c7")]
		ThermometerFull,
		[Description("0xf2c9")]
		ThermometerHalf,
		[Description("0xf2ca")]
		ThermometerQuarter,
		[Description("0xf2c8")]
		ThermometerThreeQuarters,
		[Description("0xf009")]
		ThLarge,
		[Description("0xf00b")]
		ThList,
		[Description("0xf165")]
		ThumbsDown,
		[Description("0xf164")]
		ThumbsUp,
		[Description("0xf08d")]
		Thumbtack,
		[Description("0xf3ff")]
		TicketAlt,
		[Description("0xf00d")]
		Times,
		[Description("0xf057")]
		TimesCircle,
		[Description("0xf043")]
		Tint,
		[Description("0xf204")]
		ToggleOff,
		[Description("0xf205")]
		ToggleOn,
		[Description("0xf552")]
		Toolbox,
		[Description("0xf513")]
		TradeFederation,
		[Description("0xf25c")]
		Trademark,
		[Description("0xf238")]
		Train,
		[Description("0xf224")]
		Transgender,
		[Description("0xf225")]
		TransgenderAlt,
		[Description("0xf1f8")]
		Trash,
		[Description("0xf2ed")]
		TrashAlt,
		[Description("0xf1bb")]
		Tree,
		[Description("0xf181")]
		Trello,
		[Description("0xf262")]
		Tripadvisor,
		[Description("0xf091")]
		Trophy,
		[Description("0xf0d1")]
		Truck,
		[Description("0xf4de")]
		TruckLoading,
		[Description("0xf4df")]
		TruckMoving,
		[Description("0xf553")]
		Tshirt,
		[Description("0xf1e4")]
		Tty,
		[Description("0xf173")]
		Tumblr,
		[Description("0xf174")]
		TumblrSquare,
		[Description("0xf26c")]
		Tv,
		[Description("0xf1e8")]
		Twitch,
		[Description("0xf099")]
		Twitter,
		[Description("0xf081")]
		TwitterSquare,
		[Description("0xf42b")]
		Typo3,
		[Description("0xf402")]
		Uber,
		[Description("0xf403")]
		Uikit,
		[Description("0xf0e9")]
		Umbrella,
		[Description("0xf0cd")]
		Underline,
		[Description("0xf0e2")]
		Undo,
		[Description("0xf2ea")]
		UndoAlt,
		[Description("0xf404")]
		Uniregistry,
		[Description("0xf29a")]
		UniversalAccess,
		[Description("0xf19c")]
		University,
		[Description("0xf127")]
		Unlink,
		[Description("0xf09c")]
		Unlock,
		[Description("0xf13e")]
		UnlockAlt,
		[Description("0xf405")]
		Untappd,
		[Description("0xf093")]
		Upload,
		[Description("0xf287")]
		Usb,
		[Description("0xf007")]
		User,
		[Description("0xf406")]
		UserAlt,
		[Description("0xf4fa")]
		UserAltSlash,
		[Description("0xf4fb")]
		UserAstronaut,
		[Description("0xf4fc")]
		UserCheck,
		[Description("0xf2bd")]
		UserCircle,
		[Description("0xf4fd")]
		UserClock,
		[Description("0xf4fe")]
		UserCog,
		[Description("0xf4ff")]
		UserEdit,
		[Description("0xf500")]
		UserFriends,
		[Description("0xf501")]
		UserGraduate,
		[Description("0xf502")]
		UserLock,
		[Description("0xf0f0")]
		UserMd,
		[Description("0xf503")]
		UserMinus,
		[Description("0xf504")]
		UserNinja,
		[Description("0xf234")]
		UserPlus,
		[Description("0xf0c0")]
		Users,
		[Description("0xf509")]
		UsersCog,
		[Description("0xf21b")]
		UserSecret,
		[Description("0xf505")]
		UserShield,
		[Description("0xf506")]
		UserSlash,
		[Description("0xf507")]
		UserTag,
		[Description("0xf508")]
		UserTie,
		[Description("0xf235")]
		UserTimes,
		[Description("0xf407")]
		Ussunnah,
		[Description("0xf2e7")]
		Utensils,
		[Description("0xf2e5")]
		UtensilSpoon,
		[Description("0xf408")]
		Vaadin,
		[Description("0xf221")]
		Venus,
		[Description("0xf226")]
		VenusDouble,
		[Description("0xf228")]
		VenusMars,
		[Description("0xf237")]
		Viacoin,
		[Description("0xf2a9")]
		Viadeo,
		[Description("0xf2aa")]
		ViadeoSquare,
		[Description("0xf492")]
		Vial,
		[Description("0xf493")]
		Vials,
		[Description("0xf409")]
		Viber,
		[Description("0xf03d")]
		Video,
		[Description("0xf4e2")]
		VideoSlash,
		[Description("0xf40a")]
		Vimeo,
		[Description("0xf194")]
		VimeoSquare,
		[Description("0xf27d")]
		VimeoV,
		[Description("0xf1ca")]
		Vine,
		[Description("0xf189")]
		Vk,
		[Description("0xf40b")]
		Vnv,
		[Description("0xf45f")]
		VolleyballBall,
		[Description("0xf027")]
		VolumeDown,
		[Description("0xf026")]
		VolumeOff,
		[Description("0xf028")]
		VolumeUp,
		[Description("0xf41f")]
		Vuejs,
		[Description("0xf554")]
		Walking,
		[Description("0xf555")]
		Wallet,
		[Description("0xf494")]
		Warehouse,
		[Description("0xf18a")]
		Weibo,
		[Description("0xf496")]
		Weight,
		[Description("0xf1d7")]
		Weixin,
		[Description("0xf232")]
		Whatsapp,
		[Description("0xf40c")]
		WhatsappSquare,
		[Description("0xf193")]
		Wheelchair,
		[Description("0xf40d")]
		Whmcs,
		[Description("0xf1eb")]
		Wifi,
		[Description("0xf266")]
		WikipediaW,
		[Description("0xf410")]
		WindowClose,
		[Description("0xf2d0")]
		WindowMaximize,
		[Description("0xf2d1")]
		WindowMinimize,
		[Description("0xf2d2")]
		WindowRestore,
		[Description("0xf17a")]
		Windows,
		[Description("0xf4e3")]
		WineGlass,
		[Description("0xf514")]
		WolfPackBattalion,
		[Description("0xf159")]
		WonSign,
		[Description("0xf19a")]
		Wordpress,
		[Description("0xf411")]
		WordpressSimple,
		[Description("0xf297")]
		Wpbeginner,
		[Description("0xf2de")]
		Wpexplorer,
		[Description("0xf298")]
		Wpforms,
		[Description("0xf0ad")]
		Wrench,
		[Description("0xf412")]
		Xbox,
		[Description("0xf168")]
		Xing,
		[Description("0xf169")]
		XingSquare,
		[Description("0xf497")]
		XRay,
		[Description("0xf19e")]
		Yahoo,
		[Description("0xf413")]
		Yandex,
		[Description("0xf414")]
		YandexInternational,
		[Description("0xf23b")]
		YCombinator,
		[Description("0xf1e9")]
		Yelp,
		[Description("0xf157")]
		YenSign,
		[Description("0xf2b1")]
		Yoast,
		[Description("0xf167")]
		Youtube,
		[Description("0xf431")]
		YoutubeSquare
	}
}